Data Manipulation

La classe tensor est l'interface principale pour le stockage et la manipulation de données en deep learning.


In [38]:
import torch

In [39]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [40]:
print(f"Chacune de ces valeurs est appelée élément du tenseur, le tenseur x contient {x.numel()} éléments")

Chacune de ces valeurs est appelée élément du tenseur, le tenseur x contient 12 éléments


In [41]:
x.shape

torch.Size([12])

Ici on voit que la taille contient une seule valeur ou un seul élément car on travaille avec un vecteur

In [42]:
X = x.reshape(3,4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [43]:
X.shape

torch.Size([3, 4])

In [44]:
X = x.reshape(-1, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

ou

In [45]:
X = x.reshape(3, -1)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [46]:
X = torch.ones((2,3,4))
X

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [47]:
parameters = torch.randn(3,4)
parameters

tensor([[-1.2499,  0.4669, -0.3514, -1.1241],
        [-0.4832,  0.9416, -0.6702,  0.6472],
        [-0.3978,  0.9575,  1.7491, -0.5674]])

In [48]:
X = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
X

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

Indexing & Slicing

In [49]:
X[-1]

tensor([4, 3, 2, 1])

In [50]:
X[1:3]

tensor([[1, 2, 3, 4],
        [4, 3, 2, 1]])

In [51]:
X[2,3] = 20
X

tensor([[ 2,  1,  4,  3],
        [ 1,  2,  3,  4],
        [ 4,  3,  2, 20]])

In [52]:
X[:2, :] = 12
X

tensor([[12, 12, 12, 12],
        [12, 12, 12, 12],
        [ 4,  3,  2, 20]])

Operations

In [53]:
torch.exp(x)

tensor([1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02,
        4.0343e+02, 1.0966e+03, 2.9810e+03, 8.1031e+03, 2.2026e+04, 5.9874e+04])

In [54]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])

In [55]:
x+y, x-y, x*y , x/y, x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

On peut aussi concatener plusieurs tenseurs rien qu'en précisant l'axe

In [56]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([
    [2.0, 1, 4, 3],
    [1, 2, 3, 4],
    [4, 3, 2, 1]
])
X, Y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]))

In [57]:
Z = torch.concat((X,Y), dim=0)
Z

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [58]:
W = torch.concat((X, Y), dim=1)
W

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [59]:
X, Y
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [60]:
print(f"Somme de tous les éléments du tenseur X: {X.sum()}")

Somme de tous les éléments du tenseur X: 66.0


In [61]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [62]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

Saving memory

In [63]:
before = id(Y)
Y = Y + X
id(Y) == before

False

In [64]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 1716200670464
id(Z): 1716200670464


In [65]:
before = id(X)
X += Y
id(X) == before

True

In [66]:
X, Y

(tensor([[ 2.,  3.,  8.,  9.],
         [ 9., 12., 15., 18.],
         [20., 21., 22., 23.]]),
 tensor([[ 2.,  2.,  6.,  6.],
         [ 5.,  7.,  9., 11.],
         [12., 12., 12., 12.]]))

In [67]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B), A, B

(numpy.ndarray,
 torch.Tensor,
 array([[ 2.,  3.,  8.,  9.],
        [ 9., 12., 15., 18.],
        [20., 21., 22., 23.]], dtype=float32),
 tensor([[ 2.,  3.,  8.,  9.],
         [ 9., 12., 15., 18.],
         [20., 21., 22., 23.]]))

In [68]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

EXERCICES

Run the code in this section. Change the conditional statement X == Y to X < Y or X >
Y, and then see what kind of tensor you can get.

In [69]:
X, Y

(tensor([[ 2.,  3.,  8.,  9.],
         [ 9., 12., 15., 18.],
         [20., 21., 22., 23.]]),
 tensor([[ 2.,  2.,  6.,  6.],
         [ 5.,  7.,  9., 11.],
         [12., 12., 12., 12.]]))

In [70]:
X == Y, X > Y, X < Y

(tensor([[ True, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[False,  True,  True,  True],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

On obtient des tenseurs avec des valeurs binaires différentes en fonction de l'opérateur logique utilisé.

Replace the two tensors that operate by element in the broadcasting mechanism with
other shapes, e.g., 3-dimensional tensors. Is the result the same as expected?

In [71]:
print(X.shape, Y.shape)

torch.Size([3, 4]) torch.Size([3, 4])


In [72]:
X, Y

(tensor([[ 2.,  3.,  8.,  9.],
         [ 9., 12., 15., 18.],
         [20., 21., 22., 23.]]),
 tensor([[ 2.,  2.,  6.,  6.],
         [ 5.,  7.,  9., 11.],
         [12., 12., 12., 12.]]))

In [73]:
Z = X + Y
print(Z.shape)
Z

torch.Size([3, 4])


tensor([[ 4.,  5., 14., 15.],
        [14., 19., 24., 29.],
        [32., 33., 34., 35.]])

Pas de vrai broadcasting